clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1 # CI does not need commit history
      recursive: true

pipeline:
  install:
    when:
      event:
        - pull_request
    image: node:18.6.0
    commands:
      - yarn install
  lint:
    when:
      event:
        - pull_request
    image: node:18.6.0
    commands:
      - yarn workspace foundkey-js run lint
